### ISSUE TITLE
Document default parameters for parameters

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/malariasimulation#107]
We want to see the values for the default parameters at a distance on `get_parameters`

**Comment by htopazian** [comment]
**Need default values for:** 
drug_efficacy
drug_rel_c
drug_prophilaxis_shape
drug_prophilaxis_scale
severe_prevalence_rendering_min_ages
severe_prevalence_rendering_max_ages
severe_incidence_rendering_min_ages
severe_incidence_rendering_max_ages

**Need to document and provide default values for:** 
bednet_timesteps
bednet_coverages
bednet_retention
spraying_timesteps
spraying_coverages
rtss_timesteps
rtss_min_ages
rtss_max_ages
rtss_boosters
rtss_booster_coverage

**Listed in get_parameters, but can't find in any functions:**
tbv_frequency
clinical_incidence_rendering_min_ages
clinical_incidence_rendering_max_ages
ft

**Comment by giovannic** [comment]
Sweet!

> *Listed in get_parameters, but can't find in any functions:*
> tbv_frequency
> ft

Great catch! These are outdated, let's remove them.

> clinical_incidence_rendering_min_ages
> clinical_incidence_rendering_max_ages

I've often been asked for clinical incidence between 0 and 5yo, so we can set these to 0 and 5 * 365.

> Need default values for:
> drug_efficacy
> drug_rel_c
> drug_prophilaxis_shape
> drug_prophilaxis_scale
> severe_prevalence_rendering_min_ages
> severe_prevalence_rendering_max_ages
> severe_incidence_rendering_min_ages
> severe_incidence_rendering_max_ages
> 
> Need to document and provide default values for:
> bednet_timesteps
> bednet_coverages
> bednet_retention
> spraying_timesteps
> spraying_coverages
> rtss_timesteps
> rtss_min_ages
> rtss_max_ages
> rtss_boosters
> rtss_booster_coverage

These seem fine as they are. By default all these things are turned off. If we set defaults, they'll give results we don't intend.

The only extra information I could suggest is to look at R/drug_parameters.R for the drug_* parameters.
