### ISSUE TITLE
Error when running multiple simulations

### ISSUE THREAD

**Issue by jhellewell14** [mrc-ide/malariasimulation#168]
I'm encountering an error when trying to generate multiple simulations. This is the error:

```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

I think it stems from the call to  `rbind` [here](https://github.com/mrc-ide/malariasimulation/blob/aace0c5f212285d22cff12b519cbc62daf79624b/R/model.R#L149) in `run_simulations_with_repetitions`.

The issue is that some of the repetitions produce output with fewer columns than usual. The error seems to arise when I'm working with very low values of `init_EIR`. 

You can generate output with different numbers of columns using this example:
```
set.seed(29350843)
p <- malariasimulation::get_parameters(list(human_population = 500))
p_low <- malariasimulation::set_equilibrium(p, init_EIR = 0.001)
p_high <- malariasimulation::set_equilibrium(p, init_EIR = 1)
r_low <- malariasimulation::run_simulation(timesteps = 100, parameters = p_low)
r_high <- malariasimulation::run_simulation(timesteps = 100, parameters = p_high)
```
This gives
```
> dim(r_low)
[1] 100  31
> dim(r_high)
[1] 100  34
```

The missing columns for the low EIR run are `rate_A_U`, `rate_D_A`, and `rate_U_S`. I think they might be missing because the run `r_low` begins at prevalence 0 and never increases so all the values for every element of those rate vectors would be `NA`. If you try and do multiple repetitions with a low EIR then some of the runs will have a few infections and some will have no infections at all so the call to `rbind` fails.

These `rate_*` columns are due to [create_rate_listener](https://github.com/mrc-ide/malariasimulation/blob/78743fb6f1d46237711d4b702f5ed821259cc52e/R/disease_progression.R#L28) being called [here](https://github.com/mrc-ide/malariasimulation/blob/aace0c5f212285d22cff12b519cbc62daf79624b/R/events.R#L126). I'm not sure why a low enough EIR eventually makes those columns disappear but I will keep digging.

**Comment by pwinskill** [comment]
It is because the event never gets scheduled, so the variable is never rendered I think @jhellewell14 .
Adding in default values fixes the above issue as in this branch: https://github.com/mrc-ide/malariasimulation/tree/bug/missing_rate_output
Should check with @giovannic as I'm sure there is a more general way to implement that fix than what I've done, but I can't work out what...

**Comment by giovannic** [comment]
@pwinskill  fantastic! `set_default` is the way

A slightly cleaner alternative would be to change create_rate_listener

```r
create_rate_listener <- function(from_state, to_state, renderer) {
  renderer$set_default(paste0('rate_', from_state, '_', to_state), NA)
  function(timestep, target) {
    renderer$render(
      paste0('rate_', from_state, '_', to_state),
      target$size(),
      timestep
    )
  }
}
```

Make a PR to dev and I'll approve it :)
