### ISSUE TITLE
Setting start and end period on routine based interventions

### ISSUE THREAD

**Issue by asiraj-nd** [mrc-ide/malariasimulation#199]
I had EPI RTS,S with start and end period set in the previous version, and now seems not recognized in the latest version. This seems to also be true with PMC. How can we set the start and ending periods, as these interventions may not apply to the entire simulation period. Thanks.

**Comment by pwinskill** [comment]
Hi @asiraj-nd 
Yes, that's correct, there was a breaking change to harmonise how we specify the timing of interventions. Similar to how some other interventions are parameterised you can now set the coverages and associated timesteps for coverages for interventions such as RTSS and PMC.

Take a look at the help for `coverage` and `timesteps` arguments in, for example `?set_rtss_epi()`. It should be quite quick to update your setup.

**Comment by pwinskill** [comment]
This is the associated PR if you wanted to look more closely: 
https://github.com/mrc-ide/malariasimulation/pull/179

**Comment by giovannic** [comment]
We also make [tags](https://github.com/mrc-ide/malariasimulation/releases) in case you would like to fix your model version and update on your own terms. For example, you can install v1.4.1 with `remotes::install_github('mrc-ide/malariasimulation@v1.4.1')`

**Comment by asiraj-nd** [comment]
Great. Thanks @pwinskill and @giovannic!
