### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/malariasimulation#212]
This may be better suited to an individual issue (let me know if so @giovannic and I can write it up there). But one of the suggested additions during the Malariaverse workshop was for a progress bar in malariasimulation. 

Is this something you've considered? Seems like a timestep-tick bar could be a reasonably good predictor of progression time.

**Comment by giovannic** [comment]
Should be a simple process:

```r
function(t) {
  cat(paste0('\rtimestep: ', t))
}
```

Would have to come up with some sensible logic/parameterisation to turn it on and off for hpc/local builds.

**Comment by pwinskill** [comment]
Is a custom implementation better than an additional dependency? I'm never sure how to judge that choice.
I'm thinking of https://cran.r-project.org/web/packages/progress/index.html authored by our very own RF

**Comment by giovannic** [comment]
Looks good! It's a pretty light package
