### ISSUE TITLE
Export run_resumable_simulation into namespace

### ISSUE THREAD

**Issue by lmhaile** [mrc-ide/malariasimulation#314]
Hi @giovannic  and @plietar ! 

I might be missing something here, but I believe `run_resumable_simulation` needs to be imported into the malariasimulation namespace via a `@import` call. Hoping to test the functionality, and I think this is my issue!

https://github.com/mrc-ide/malariasimulation/blob/3ecb72a07b90b6c98f515738de3355f5e19d1ace/R/model.R#L92-L104

**Comment by plietar** [comment]
Yes I believe you’re right (albeit I think it’s an `@export` that is needed). I’ll make a fix tomorrow. In the meantime you can work around by using a triple colon, eg `malariasimulation:::run_resumable_simulation`.

I’d be curious to hear more your use case! You’re the first person to try this feature in practice, hence the snags. Let me know if anything else comes up. I’ve been meaning to write some vignette about it but haven’t got around to it yet.

**Comment by lmhaile** [comment]
Fantastic, thanks Paul! For now the triple colon works great.

@htopazian and I are setting up some context-specific runs where vaccine efficacy and carrying capacity parameters change halfway through the simulation (IE, modelling the introduction of mosquito gene drives and blood-stage vaccines). I launched a few test models yesterday and they seem to have completed, so will plot them to see how they look! 

The code is in development but here is my use case:  

https://github.com/mrc-ide/malaria_no_more/blob/e0826db8b1b02e76b1e71f6a7754c0e759289ddc/src/model_country/MNM_functions.R#L250-L294

Also happy to write a vignette for this based on the tests, since I'll be playing around with this feature today anyway. Thanks for your help!

**Comment by plietar** [comment]
Does automatic closing of issues when merging a PR not work on this repo?

**Comment by plietar** [comment]
Ah I think it's because the PR was merged onto `dev`, which isn't the "default branch"
