### ISSUE TITLE
Vector control resistance

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/malariasimulation#58]
Currently bednet paramters `rn` and `dn` are are constant for the whole of the simulation:

```r
# ...
# set bednet profile
bednetparams <- get_parameters(list(
    rn = .56,
    rnm = .24,
    dn0 = .533,
    gamman = 2.64 * 365
))

# set bednet strategy
bednetparams <- set_bednets(
  bednetparams,
  timesteps = 4:7 * year,
  coverages = rep(.8, 4),
  retention = 5 * year
)
# ...
```

But in actuality mosquitoes become resistant to bednets. We would like to model changes to dn/rn. Questions:

 * are the dn/rn changes normally modelled as a curve or discrete changes?
 * And are these changes independent of the type of bednet? See #54

**Comment by giovannic** [comment]
Initial version will use modifications from [here](https://www.nature.com/articles/s41467-018-07357-w)

IRS resistance:

- [ ] calculate k (proportion of successful feeds), m (detterance), l (mortality) values based on k, l, m parameters and time since spray
<img width="605" alt="Screenshot 2021-06-03 at 13 49 27" src="https://user-images.githubusercontent.com/2605711/120647444-86187e00-c472-11eb-99a2-8230783ce210.png">

- [ ] calculate k', l', j' values according to...
<img width="475" alt="Screenshot 2021-06-03 at 13 50 33" src="https://user-images.githubusercontent.com/2605711/120647746-d7c10880-c472-11eb-870e-c724ca6e4345.png">

- [ ] update d_s, r_s and s_s calculations to match...
<img width="501" alt="Screenshot 2021-06-03 at 13 54 15" src="https://user-images.githubusercontent.com/2605711/120648115-31293780-c473-11eb-9e5f-b6f597f70fda.png">

Bednet resistance:

- [ ] make rn, dn0 and gamman time-varying

Update vignettes to make examples

**Comment by EllieSherrardSmith** [comment]
_are the dn/rn changes normally modelled as a curve or discrete changes?_

We have both options. Ben Lambert has a version with the curve but I am making discrete changes. I think for now if we can have these as discrete changes that is better. Ideally, we would have these coinciding with net distribution. 

We could have itn_cov 0.6, distribution_year 3 and distribution_time 156 (day of the year in year x)
Working with efficacy 
rn = .56,
rnm = .24,
dn0 = .533,
gamman = 2.64 * 365

Then (a few years later as resistance increases to some arbitrary score which is worked out outside the model!)
We could have itn_cov_2 0.65, distribution_year_2 6 and distribution_time_2 26 (day of the year in year x)
Working with efficacy e.g.
rn_2 = .5,
rnm_2 = .24,
dn0_2 = .45,
gamman_2 = 2 * 365

for as many changes as is possible!

_And are these changes independent of the type of bednet? See #54_

The estimate of efficacy is linked to the bednet type so we can certainly update to this - I have a function that can work out the params (posterior distributions for these) for any net type we have profiled for any resistance level. So we could embed this. Though, we are likely to iteratively update this (next challenge is durability of nets and then using other info to define resistance, different to susceptibility bioassays). It also needs a bit of storage space as the Bayes outputs for fits to the raw data are quite large. I think storing these in the shared drive or providing just the median estimate is possible? 

The ultimate impact params are still rn, rnm, dn and gamman (the external function spits out the e.g. 2.64 so just need to multiply by 365 for the gamman input)

**Comment by patrickgtwalker** [comment]
How much additional effort/computation would user-specified curves take? I'm thinking along the lines of the drug distribution set-up where you can just pass any shape you want (discrete steps, output from parametric curves, your own made up numbers etc....) If you had that flexibility would guess easy to add functions to let user pick whatever they want and easy to write a function that takes discrete changes (akin to the interpolate function in odin?). 

I'm guessing if you're calculating new infections at each step (so are using implicitly evaluating some formulation of the parameters) perhaps not much but if it's some fancy time-to-event then could add a lot? 

re your comment about storage space Ellie - could you not just store a subset of draws (e.g. 50/100 or so as in the model_parms_x.txt files in the old c++)?
