### ISSUE TITLE
Mosquitoes should have a random extrinsic incubation period

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/malariasimulation#70]
Mosquitoes currently have a fixed incubation period of parameters$dem. But it should be drawn from a log_uniform distribution

**Comment by IsaacStopard** [comment]
Hey @giovannic - we have a PDF for the EIP, should be able to use inverse transform sampling to randomly draw EIP values. I'm not familiar with this model but let me know if that would be useful.

**Comment by giovannic** [comment]
Oh. V. cool! Thanks :) I'll ping you for those when I get round to implementing this.

The steps to do this are:

 - [ ] draw waiting time for mosquitoes in EIP at the beginning of the simulation [here](https://github.com/mrc-ide/malariasimulation/blob/master/R/processes.R#L382)
 - [ ] draw waiting time for mosquitoes who enter EIP during the simulation [here](https://github.com/mrc-ide/malariasimulation/blob/master/R/mosquito_biology.R#L174)

**Comment by IsaacStopard** [comment]
Cool - I think all you need is this function and the "zipfR" package (or I think the inverse regularised gamma function is also availlable in the Boost library for C++). Can provide the posterior distributions for a, b, mu and k when you need them. 
```
EIP_rng <- function(a, b, mu, k, n = 1){
  p <- runif(n)
  bt <- ((-(p * (1 - (k / (k + mu))^k) - 1)/(k^k))^(-1/k) - k) / mu
  return((Rgamma.inv(a, bt, lower = TRUE)/b))
}
```

**Comment by giovannic** [comment]
I'm closing this since mosquitoes currently have a random exponential EIP. But, we can re-open/re-name this if someone needs the gamma
